### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/tomlib#33]
Dear @LiamNaughton and @gpfeiffer it would be great to have a tomlib 1.2.10 release -- nothing major changed since 1.2.9, just a bunch of minor janitorial things, but nevertheless, they should reach users.

If you are OK with it, I can do it right away (it'll be < 5 minutes work for me). Or if you prefer, you can of course also do it yourself.

**Comment by gpfeiffer** [comment]
Hi Max,

Yes please go ahead if it's really only a couple of minutes.
Before I remember all the details of the process I might
break more than what was changed in this update ...

Thanks and all the best,
Götz

------------------------------------------------------------------------
***@***.***
Mathematics, University of Galway, Ireland.        phone +353-91-49-3591

________________________________________
From: Max Horn ***@***.***>
Sent: 11 January 2024 13:08
To: gap-packages/tomlib
Cc: Pfeiffer, Gotz; Mention
Subject: [gap-packages/tomlib] New release (Issue #33)

EXTERNAL EMAIL: This email originated outside the University of Galway. Do not open attachments or click on links unless you believe the content is safe.
RÍOMHPHOST SEACHTRACH: Níor tháinig an ríomhphost seo ó Ollscoil na Gaillimhe. Ná hoscail ceangaltáin agus ná cliceáil ar naisc mura gcreideann tú go bhfuil an t-ábhar sábháilte.


Dear @LiamNaughton<https://github.com/LiamNaughton> and @gpfeiffer<https://github.com/gpfeiffer> it would be great to have a tomlib 1.2.10 release -- nothing major changed since 1.2.9, just a bunch of minor janitorial things, but nevertheless, they should reach users.

If you are OK with it, I can do it right away (it'll be < 5 minutes work for me). Or if you prefer, you can of course also do it yourself.

**Comment by LiamNaughton** [comment]
I agree with Götz :-)Thanks Max Sent from my iPhoneOn 11 Jan 2024, at 14:51, Götz Pfeiffer ***@***.***> wrote:﻿
Hi Max,

Yes please go ahead if it's really only a couple of minutes.
Before I remember all the details of the process I might
break more than what was changed in this update ...

Thanks and all the best,
Götz

------------------------------------------------------------------------
***@***.***
Mathematics, University of Galway, Ireland.        phone +353-91-49-3591

________________________________________
From: Max Horn ***@***.***>
Sent: 11 January 2024 13:08
To: gap-packages/tomlib
Cc: Pfeiffer, Gotz; Mention
Subject: [gap-packages/tomlib] New release (Issue #33)

EXTERNAL EMAIL: This email originated outside the University of Galway. Do not open attachments or click on links unless you believe the content is safe.
RÍOMHPHOST SEACHTRACH: Níor tháinig an ríomhphost seo ó Ollscoil na Gaillimhe. Ná hoscail ceangaltáin agus ná cliceáil ar naisc mura gcreideann tú go bhfuil an t-ábhar sábháilte.


Dear @LiamNaughton<https://github.com/LiamNaughton> and @gpfeiffer<https://github.com/gpfeiffer> it would be great to have a tomlib 1.2.10 release -- nothing major changed since 1.2.9, just a bunch of minor janitorial things, but nevertheless, they should reach users.

If you are OK with it, I can do it right away (it'll be < 5 minutes work for me). Or if you prefer, you can of course also do it yourself.

**Comment by fingolfin** [comment]
Done!
